
model:
    base: 'vgg16'
    arch: 'fcn32s'

n_classes: 21

data:
    dataset: pascal
    train_split: train_aug
    val_split: train_aug_val
    img_rows: 338
    img_cols: 338
    #img_rows: "same"
    #img_cols: "same"
    path: /data/pascal/VOCdevkit/VOC2012/
    sbd_path: /data/pascal/benchmark_RELEASE/

training:
    loss:
        name: 'cross_entropy'
        size_average: False


